-- RUN THIS IN YOUR SUPABASE SQL EDITOR TO SETUP RSVP

-- 1. Create RSVPs table
create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  wedding_id bigint references public.weddings(id) on delete cascade,
  name text not null,
  email text,
  phone text, -- Added phone column
  attending text, -- 'yes', 'no'
  guests_count integer default 1,
  meal_preference text,
  message text
);

-- 2. Enable RLS
alter table public.rsvps enable row level security;

-- 3. Policies
-- Allow anyone to Insert (Public RSVP)
create policy "Allow Public Insert RSVPs"
on public.rsvps for insert
with check ( true );

-- Allow Admin (Auth users) to Select (View/Download)
create policy "Allow Auth Select RSVPs"
on public.rsvps for select
using ( auth.role() = 'authenticated' );
