-- RUN THIS IN YOUR SUPABASE SQL EDITOR

-- 1. Create the 'weddings' table if you haven't already
create table if not exists public.weddings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  slug text unique,
  bride_name text,
  bride_image text,
  bride_description text,
  groom_name text,
  groom_image text,
  groom_description text,
  date text,
  location text,
  venue_name text,
  venue_address text,
  venue_description text,
  story_part1 text,
  story_highlight text,
  story_part2 text,
  ceremony_date text,
  ceremony_time text,
  ceremony_venue text,
  reception_date text,
  reception_time text,
  reception_venue text,
  reception_address text,
  dress_code text,
  dress_code_desc text,
  map_location text,
  slider_images jsonb,
  bridesmaids jsonb,
  groomsmen jsonb,
  gifts jsonb,
  gallery_images jsonb
);

-- 2. Create the Storage Bucket 'wedding-uploads' 
-- (Note: 'storage.buckets' usually requires higher privileges. 
-- If this fails, create the bucket manually in the Supabase Dashboard: Storage -> New Bucket -> 'wedding-uploads' -> Make Public)
insert into storage.buckets (id, name, public)
values ('wedding-uploads', 'wedding-uploads', true)
on conflict (id) do nothing;


-- 3. POLICIES (Simplified to avoid ownership issues)
-- We target the objects table indirectly or use specific policies that don't require altering the table itself if possible.
-- However, creating policies usually requires being the owner or having rights. 
-- Try running these separately if the above passes.

create policy "Public Access"
on storage.objects for select
using ( bucket_id = 'wedding-uploads' );

create policy "Public Insert"
on storage.objects for insert
with check ( bucket_id = 'wedding-uploads' );
